#include: "rules/snATACseq_cellRanger.smk"
include: "rules/snATACseq_processing.smk"
include: "rules/snATACseq_LDSR.smk"
#include:  "rules/snATACseq_QC_LSI_params.smk" 

rule all:
    input:
#        expand("../results/snATACseq_CR-atac_1.2.0/{SAMPLE}.stamp", SAMPLE=config["SAMPLES_ATAC"]),
#        expand("../results/snATACseq_CR-atac_1.2.0/{SAMPLE_AGGR}.aggr", SAMPLE_AGGR=config["SAMPLES_ATAC_AGGR"]),
        expand("../results/archR_data_processing/snATACseq_QC_{REGION}.html", REGION = config['ATAC_REGIONS']), # Can remove this once testing complete
        expand("../results/archR_data_processing/snATACseq_cluster_QC_FC.html"),
        expand("../results/archR_data_processing/snATACseq_unconstrained_integration_{REGION}.html", REGION = config['ATAC_REGIONS']), 
#        expand("../results/archR_data_processing/snATACseq_pseudo-bulk-reps_and_peak_calling_{REGION}.html", REGION = config['ATAC_REGIONS']),
        expand("../results/archR_data_processing/snATACseq_cluster_ID_geneExpMatrix_{REGION}.html", REGION = config['ATAC_REGIONS']),
        expand("../results/archR_data_processing/snATACseq_call_peaks_ext_500bp_{REGION}.html", REGION = config['ATAC_REGIONS']),
        "../results/archR_data_processing/snATACseq_additional_analyses.html" ,
        expand("../results/rmarkdown_reports/snATACseq_LDSR_baseline.v1.2_{EXT}_report.html", EXT = config['PEAK_EXTENSION']),
#        expand("../results/archR_data_processing/snATACseq_remove_batch_effects_{REGION}.html", REGION = config['ATAC_REGIONS']), # Can remove this once testing complete
#        expand("../results/snATACseq_unconstrained_integration_{REGION}.html", REGION = config['ATAC_REGIONS']) 
#         expand("../results/QC_LSI_params/snATACseq_QC_{REGION}_LSI_{LSI_PARAM}.html", REGION = config['ATAC_REGIONS'], LSI_PARAM = config['LSI_PARAMS'])
