---
title: "snATAC ArchR - Additional analyses - `r REGION`"
author: "Darren Cameron"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output: 
  html_document:
    theme: paper
---

snATACseq analysis with ArchR - Additional analyses.

*** 

### **Results** {.tabset}

#### **Motif Enrichment** {.tabset}

##### **FC**

Motifs enriched cell-specific peaks

***

```{R, motifs_cell_specifc_FC, fig.dim = c(10,5), echo=FALSE}
ComplexHeatmap::draw(motif_heatmap_FC, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

***

##### **GE**

Motifs enriched cell-specific peaks

***

```{R, motifs_cell_specifc_GE, fig.dim = c(10,5), echo=FALSE}
ComplexHeatmap::draw(motif_heatmap_GE, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

***

#### **HARs Enrichment** {.tabset}

##### **FC**

HARs enriched cell-specific peaks

***

```{R, HARs_cell_specifc_FC, fig.dim = c(10,5), echo=FALSE}
ComplexHeatmap::draw(HARs_heatmap_FC, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

***

##### **GE**

HARs enriched cell-specific peaks

***

```{R, HARs_cell_specifc_GE, fig.dim = c(10,5), echo=FALSE}
ComplexHeatmap::draw(HARs_heatmap_GE, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```

***

#### FC Footprints {.tabset}

```{r FC footprints, results='asis', echo=FALSE}
for(i in 1:length(FC_motifs_recode_all)) {
  cat('##### ', FC_motifs_recode_all[i], ' \n')
  plot <- get(paste0('FC_', FC_motifs_recode_all[i], '_footprint_plot'))
  print(plot)
  cat('\n \n')
}

```

#### GE Footprints {.tabset}

```{r GE footprints, results='asis', echo=FALSE}
for(i in 1:length(GE_motifs_recode_all)) {
  cat('##### ', GE_motifs_recode_all[i], ' \n')
  plot <- get(paste0('GE_', GE_motifs_recode_all[i], '_footprint_plot'))
  print(plot)
  cat('\n \n')
}

```
